// ORM.
const DatabaseConnection = require('#db');
// Definition (nodester).
const defineModel = require('nodester/models/define');


const refreshToken = defineModel(DatabaseConnection, 'RefreshToken',
	(DataTypes) => ({
		id: {
			type: DataTypes.INTEGER.UNSIGNED,
			allowNull: false,
			primaryKey: true,
			autoIncrement: true,
			_autoGenerated: true
		},

		user_id: {
			type: DataTypes.INTEGER.UNSIGNED,
			allowNull: false
		},

		token_hash: {
			type: DataTypes.STRING,
			allowNull: false
		},

		jti: {
			type: DataTypes.STRING,
			allowNull: false,
			unique: true
		},

		revoked: {
			type: DataTypes.BOOLEAN,
			defaultValue: false
		},

		expires_at: {
			type: DataTypes.DATE,
			allowNull: false
		},

		last_used_at: {
			type: DataTypes.DATE
		},
	}),
	{
		// Allow only "soft" delete.
		paranoid: true
	}
);

// Hooks:
refreshToken.associate = ({ User, ...models }) => {
	refreshToken.belongsTo(User, {
		as: 'user',
		through: 'user_id'
	});
}

module.exports = refreshToken;
