// ORM.
const DatabaseConnection = require('#db');
// Definition (nodester).
const defineModel = require('nodester/models/define');


const user = defineModel(DatabaseConnection, 'User',
	(DataTypes) => ({
		id: {
			type: DataTypes.INTEGER.UNSIGNED,
			allowNull: false,
			primaryKey: true,
			autoIncrement: true,
			_autoGenerated: true
		},

		email: {
			type: DataTypes.STRING(300),
			allowNull: false,
			unique: true
		},

		password_hash: {
			type: DataTypes.STRING,
			allowNull: false,
		},

		token_version: {
			type: DataTypes.INTEGER.UNSIGNED,
			allowNull: false,
			defaultValue: 0
		}
	}),
	{
		// Allow only "soft" delete.
		paranoid: true
	}
);

// Hooks:
user.associate = ({ User, ...models }) => {
	user.hasMany(models.RefreshToken, {
		as: 'refresh_tokens',
		foreignKey: 'user_id'
	});
}

module.exports = user;
