const {
	JWT_PRIVATE_KEY,
	JWT_PUBLIC_KEY,
	JWT_KID,
	JWT_ISSUER,
	JWT_AUDIENCE,
	JWT_ACCESS_TOKEN_LIFETIME,
	JWT_REFRESH_TOKEN_LIFETIME,
} = process.env;


module.exports = {
	PRIVATE_KEY: JWT_PRIVATE_KEY,
	PUBLIC_KEY: JWT_PUBLIC_KEY,
	KID: JWT_KID || 'default',
	ISSUER: JWT_ISSUER || 'nodester-app',
	AUDIENCE: JWT_AUDIENCE || JWT_ISSUER || 'nodester-app',
	ACCESS_TOKEN_LIFETIME: parseInt(JWT_ACCESS_TOKEN_LIFETIME || '900', 10), // default 15 minutes
	REFRESH_TOKEN_LIFETIME: parseInt(JWT_REFRESH_TOKEN_LIFETIME || '2592000', 10), // default 30 days
}

